#!/usr/bin/env zsh

#region zinit
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust
#endregion

#region trapd00r/LS_COLORS
zinit lucid reset \
 atclone"[[ -z ${commands[dircolors]} ]] && local P=g
    \${P}sed -i '/DIR/c\DIR 38;5;63;1' LS_COLORS; \
    \${P}dircolors -b LS_COLORS > clrs.zsh" \
 atpull'%atclone' pick'clrs.zsh' nocompile'!' \
 atload'zstyle ":completion:*:default" list-colors "${(s.:.)LS_COLORS}";' for \
    trapd00r/LS_COLORS
#endregion

#region zsh-users/zsh-completions
zinit wait'0a' lucid blockf depth=1 \
    atload'zicompinit; zicdreplay' \
        for @zsh-users/zsh-completions
#endregion

#region zsh-users/zsh-autosuggestions
zinit lucid light-mode \
    for @zsh-users/zsh-autosuggestions
#endregion

#region zdharma-continuum/fast-syntax-highlighting
zinit lucid light-mode \
    atinit'typeset -gA FAST_HIGHLIGHT; FAST_HIGHLIGHT[git-cmsg-len]=73' \
        for @zdharma-continuum/fast-syntax-highlighting
#endregion

#region starship/starship
zinit ice as'command' from'gh-r' \
    atclone'./starship init zsh > init.zsh; ./starship completions zsh > _starship' atpull'%atclone' \
    src'init.zsh'
zinit light starship/starship
#endregion

#region jimhester/per-directory-history
zinit lucid light-mode \
    for @jimhester/per-directory-history
#endregion

#region jdx/mise
zinit lucid light-mode as'command' from'gh-r' \
    atpull'%atclone' \
        for jdx/usage

zinit lucid light-mode as'command' from'gh-r' \
    atclone'chmod +x mise*; ./mise* completion zsh > _mise' atpull'%atclone' \
    mv'mise* -> mise' \
    atload='eval "$(mise activate zsh)"' \
        for jdx/mise
#endregion

#region tmux
zinit id-as'tmux' has'mise' lucid nocompile \
    atclone'mise use -g tmux' atpull'%atclone' \
        for @zdharma-continuum/null
#endregion

#region OMZP::tmux
zinit wait lucid light-mode \
    atinit'export ZSH_TMUX_AUTOSTART=true; export ZSH_TMUX_UNICODE=true' \
    atclone'curl -sOL https://github.com/ohmyzsh/ohmyzsh/raw/master/plugins/tmux/tmux.only.conf
        curl -sOL https://github.com/ohmyzsh/ohmyzsh/raw/master/plugins/tmux/tmux.extra.conf
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm' atpull='%atclone' \
    atload'unalias tds tksv tl tmuxconf; unfunction ta tad tkss to ts' \
        for @OMZP::tmux
#endregion

#region direnv
zinit id-as'direnv' has'mise' lucid nocompile \
    atclone'mise use -g tmux' atpull'%atclone' \
    atload'eval "$(direnv hook zsh)"' \
        for @zdharma-continuum/null
#endregion

#region awscli
zinit id-as'awscli' has'mise' wait'0b' lucid nocompile \
    atclone'mise use -g awscli' atpull'%atclone' \
    atload'autoload -Uz +X bashcompinit && bashcompinit; complete -C $(which aws_completer) aws' \
        for @zdharma-continuum/null
#endregion

#region alias
if (( $+commands[eza] )); then
  alias ls='eza --header --time-style long-iso'
else
  alias ls='ls --color=auto --file-type --time-style long-iso'
fi
#endregion

#region hook
chpwd() ls
#endregion

#region changing_directories
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
#endregion

#region completion
setopt NO_AUTO_MENU               # 補完時に TAB キーで選択肢を移動しない
setopt LIST_PACKED                # 補完候補を表示する際に表示を詰める
#endregion

#region history
setopt APPEND_HISTORY             # zsh が終了した際に HISTFILE を置き換えるのではなく追記する
setopt EXTENDED_HISTORY           # HISTFILE にタイムスタンプを記録する
setopt HIST_EXPIRE_DUPS_FIRST     # 重複する履歴を削除してから保存する
setopt HIST_IGNORE_ALL_DUPS       # 履歴の内容と重複する行を履歴リストに追加しない
setopt HIST_IGNORE_SPACE          # 先頭がスペースで始まる行を履歴に追加しない
setopt HIST_LEX_WORDS             # クォートされた空白を正しく取り扱う
setopt HIST_NO_STORE              # history コマンドを履歴に追加しない
setopt HIST_REDUCE_BLANKS         # 履歴に追加する際に不要な空白を取り除く
setopt HIST_SAVE_NO_DUPS          # HISTFILE に重複する履歴を保存しない
setopt HIST_VERIFY                # 履歴補完した内容を即実行せず行エディタに読み込む
setopt SHARE_HISTORY              # 複数の zsh 間で HISTFILE を共有する
#endregion

#region zle
setopt NO_BEEP                    # ビープ無効
#endregion
