#!/usr/bin/zsh

if [ -d /usr/share/git-core/contrib ]; then
    export PATH="/usr/share/git-core/contrib:$PATH"
fi

mkdir -p "$HOME/.local/bin"
export PATH="$HOME/.local/bin:$PATH"

mkdir -p "$HOME/.toolbox/bin"
export PATH="$HOME/.toolbox/bin:$PATH"

export LESSHISTFILE=-

export HISTSIZE=10000
export SAVEHIST=20000
export HISTFILE=~/.zsh_history

export EDITOR="code -r -w"

# for zdharma-continuum/zinit
skip_global_compinit=1
