#!/usr/bin/env zsh

#region zinit
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust
#endregion

#region mise
zinit id-as'mise' as'null' has'mise' \
    atload'eval "$(mise activate zsh)"' \
        for zdharma-continuum/null
#endregion

#region olets/zsh-transient-prompt
zinit wait'0' lucid light-mode \
    for olets/zsh-transient-prompt
#endregion

#region starship
zinit id-as'starship' as'null' has'starship' \
    atclone'starship init zsh > init.zsh' atpull'%atclone' \
    src'init.zsh' \
    atload'
        function _pretransit() { TRANSIENT_PROMPT_PROMPT=$(starship prompt) }
        TRANSIENT_PROMPT_PRETRANSIENT=_pretransit
        TRANSIENT_PROMPT_TRANSIENT_PROMPT=$(starship module character)' \
            for zdharma-continuum/null
#endregion

#region hook
chpwd() ls
#endregion

#region changing_directories
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
#endregion

#region completion
setopt NO_AUTO_MENU               # 補完時に TAB キーで選択肢を移動しない
setopt LIST_PACKED                # 補完候補を表示する際に表示を詰める

# completion cache mechanism
typeset -g _comp_dirty=0
typeset -g _comp_cache=${XDG_CACHE_HOME:-$HOME/.cache}/zsh/completions
[[ -d $_comp_cache ]] || mkdir -p $_comp_cache
fpath=($_comp_cache $fpath)

_gen_comp() {
    local cmd=$1; shift
    (( $+commands[$cmd] )) || return
    local f=$_comp_cache/_$cmd
    # settings.minimum_release_age = "7d"
    if [[ ! -s $f || -n $f(#qNm+7) ]]; then
        if "$@" > $f.tmp 2>/dev/null; then
            mv -f $f.tmp $f
            _comp_dirty=1
        else
            rm -f $f.tmp
        fi
    fi
}

_gen_comp mise     mise completion zsh

_gen_comp uv       uv generate-shell-completion zsh
_gen_comp starship starship completions zsh
_gen_comp herdr    herdr completion zsh
_gen_comp gh       gh completion -s zsh
_gen_comp op       op completion zsh
_gen_comp lazygit  lazygit completion zsh
unfunction _gen_comp

(( _comp_dirty )) && command rm -f ${ZDOTDIR:-$HOME}/.zcompdump{,.zwc}
unset _comp_dirty _comp_cache

zicompinit
zicdreplay

autoload -Uz bashcompinit && bashcompinit
(( $+commands[aws_completer] )) && complete -C aws_completer aws
#endregion

#region history
setopt APPEND_HISTORY             # zsh が終了した際に HISTFILE を置き換えるのではなく追記する
setopt EXTENDED_HISTORY           # HISTFILE にタイムスタンプを記録する
setopt HIST_EXPIRE_DUPS_FIRST     # 重複する履歴を削除してから保存する
setopt HIST_IGNORE_ALL_DUPS       # 履歴の内容と重複する行を履歴リストに追加しない
setopt HIST_IGNORE_SPACE          # 先頭がスペースで始まる行を履歴に追加しない
setopt HIST_LEX_WORDS             # クォートされた空白を正しく取り扱う
setopt HIST_NO_STORE              # history コマンドを履歴に追加しない
setopt HIST_REDUCE_BLANKS         # 履歴に追加する際に不要な空白を取り除く
setopt HIST_SAVE_NO_DUPS          # HISTFILE に重複する履歴を保存しない
setopt HIST_VERIFY                # 履歴補完した内容を即実行せず行エディタに読み込む
setopt SHARE_HISTORY              # 複数の zsh 間で HISTFILE を共有する
#endregion

#region zle
setopt NO_BEEP                    # ビープ無効
#endregion
