#!/usr/bin/env zsh

local directories=(
    "$HOME/.local/bin"
    "$HOME/.local/share/mise/shims"
    "$HOME/.aim/mcp-servers"
    "$HOME/.toolbox/bin"
)

for dir in "${directories[@]}"; do
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
    fi

    export PATH="$dir:$PATH"
done
