[settings]
minimum_release_age = "7d"

[settings.node]
gpg_verify = false

[env]
UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }

[tools]
usage = "latest"

node = "lts"
python = "latest"
uv = "latest"

starship = "latest"
herdr = "latest"

gh = "latest"
awscli = "latest"

op = "latest"

lazygit = "latest"

jq = "latest"
yq = "latest"
