[settings]
minimum_release_age = "7d"

[settings.node]
gpg_verify = false

[tools]
node = "lts"
uv = "latest"

starship = "latest"
herdr = "latest"

gh = "latest"
awscli = "latest"

op = "latest"

yazi = "latest"
hunk = "latest"
