name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: bats-core/bats-action@5b1e60c2ee94cb1b44a616ea4b1f466f9d6e38ef # v4.0.0
        with:
          bats-version: 1.13.0
          support-install: false
          assert-install: false
          detik-install: false
          file-install: false
      - name: Install chezmoi and apply
        run: |
          mkdir -p ~/.local/share
          ln -s "$GITHUB_WORKSPACE" ~/.local/share/chezmoi
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b ~/.local/bin apply
      - name: Run tests
        run: ~/.local/share/chezmoi/scripts/run_test.bash
